name: build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ArtemSBulgakov/buildozer-action@master
        with:
          command: buildozer android debug
          buildozer_version: master
